const experiences = [
  {
    company: "Elsevier",
    periodStart: "Jan 2023",
    periodEnd: "Present",
    position: "Software Engineer IV",
    location: "UK🇬🇧",
    descriptions: [
      "Involved in design and implementation of event-driven system based on Kafka",
      "Nurturing the growth of junior engineers and mentoring team members",
      "Work with external team for system integration",
    ],
    techStacks: ["Java", "Spring Boot", "AWS", "Apache Kafka"],
  },
  {
    company: "Capsuite",
    periodStart: "July 2022",
    periodEnd: "Dec 2022",
    position: "Software Engineer",
    location: "Hong Kong🇭🇰",
    sideNote: "Work remotely in UK🇬🇧",
    descriptions: [
      "Design and develop services beyond ERP(enterprise resource planning) system",
      "Manage a small team of engineer",
      "Achieve development progress by assigning different task to team members",
      "Provide consultation on new feature",
    ],
    techStacks: [
      "NestJs",
      "Next.js",
      "TypeScript",
      "MongoDB",
      "PostgreSQL",
      "Azure",
    ],
  },
  {
    company: "SHOPLINE",
    periodStart: "July 2021",
    periodEnd: "July 2022",
    position: "Software Engineer",
    location: "Hong Kong🇭🇰",
    descriptions: [
      "Responsible for merchant subscription",
      "Manage subscription fee collection",
      "Revamp subscription payment system",
      "Collaborate with UI designer for frontend development",
    ],
    techStacks: [
      "Ruby on Rails",
      "NestJs",
      "React",
      "TypeScript",
      "MongoDB",
      "AWS",
    ],
  },
  {
    company: "Hong Kong Tech Venture",
    periodStart: "Oct 2020",
    periodEnd: "May 2021",
    position: "Programmer II",
    location: "Hong Kong🇭🇰",
    sideNote: "Promoted since Oct 2020",
    descriptions: [
      "Lead a small team of programmer",
      "Responsible for payment service development and maintenance",
      "Cooperate with 3rd party for payment gateway integration (like Citibank and HSBC HK)",
    ],
    techStacks: ["Java 8/11", "Spring Boot", "MySQL"],
  },
  {
    company: "Hong Kong Tech Venture",
    periodStart: "July 2019",
    periodEnd: "Oct 2020",
    position: "Programmer I",
    location: "Hong Kong🇭🇰",
    descriptions: [
      "Responsible for payment service",
      "Developer for HKTVpay(Backend) - A mobile payment using QR code",
      "Involved in system design for HKTVpay(Backend)",
    ],
    techStacks: ["Java 8/11", "Spring Boot", "MySQL"],
  },
];

export default experiences;
